"use client"
import '../styles/globals.scss'
import Header from '../components/header/header'
import Option from '../components/navbar/opcion'
import Loading from './loading'
import { Suspense } from 'react'
import { SessionProvider } from 'next-auth/react'
import { createContext, useState } from 'react';
// export const metadata = {
//   title: 'Terrabellum',
//   description: 'Generated by Next.js',
// }
export  const MyContext = createContext();
export default function RootLayout({
  children,
}
// : {
//   children: React.ReactNode
// }
) { 
  const [sharedVariable, setSharedVariable] = useState('Hola, soy una variable compartida');
  const updateSharedVariable = (newValue ) => {
    setSharedVariable(newValue);
  }; 
  return (
    <html lang="en">
      <MyContext.Provider value={{ sharedVariable, updateSharedVariable }}>
        <SessionProvider >
          <body>
          <Header/>
          <div style={{margin:'120px 0 0 170px'}}>
            { <Suspense fallback={<Loading/>}>
              {children}
            </Suspense>}
          </div>
          <Option/>
          </body>
        </SessionProvider>
      </MyContext.Provider>
    </html>
  )
} 
// RootLayout.defaultProps ={
//        title: 'TerraBellum',
//        description: '.'
//    }