import '../styles/globals.scss'
import Header from '../../components/header/header'
import Option from '../../components/navbar/opcion'
import Loading from './loading'
import { Suspense } from 'react'
export const metadata = {
  title: 'Terrabellum',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <div style={{margin:'120px 133px 0 133px'}}>
        { <Suspense fallback={<Loading/>}>
          {children}
        </Suspense>}
      </div>
      <Option/>
      </body>
    </html>
  )
}
// RootLayout.defaultProps ={
//        title: 'TerraBellum',
//        description: '.'
//    }